### ISSUE TITLE
Could we move this project to pharo-containers

### ISSUE THREAD

**Issue by Ducasse** [pharo-contributions/Hashtable#2]
because we are aggregating all the external datastructure there.

**Comment by Ducasse** [comment]
Or I could clone it there because in Containers I set some convention for package and class names.

**Comment by astares** [comment]
For the records: @Ducasse refers to https://github.com/pharo-containers organization here. 

I can work on this/do it - but someone must give me permissions in the "pharo-containers" organization.

At the moment it looks like only @olekscode is member there and there is no owner. See
https://github.com/orgs/pharo-containers/people

<img width="267" alt="image" src="https://github.com/pharo-contributions/Hashtable/assets/5980033/dc6bcad9-4fed-40fc-a541-a25f22bb61df">

**Comment by astares** [comment]
@Ducasse 
Project was moved to https://github.com/pharo-containers/Hashtable and README.md has a big warning sign. I will archive this repo
