### ISSUE TITLE
Infinite loop when error caused by printString

### ISSUE THREAD

**Issue by badetitou** [pharo-contributions/Hashtable#3]
Hello, 

When an error occurs, the stack trace is printed.
For the Hashtable, it calls `#printElementsOn:`, that calls `#keysSortedSafely`, that calls `#ifError:`

But `#ifError:` is deprecated in P9 in favor of `#onErrorDo:`.
And the deprecation is CI implies printing the stackstrace (that calls `#printElementsOn:`, that calls `#keysSortedSafely`, that calls `#ifError:` and so on)

The fix can be done straightforward. But then, the hashtable package will not be available for P6, P7, and P8.

3 options: 
1- create a specific configuration in a baseline that overrides the `#keysSortedSafely` method with the correct name.
2- update the method `#keysSortedSafely` and release a version 2.0.0 of the project (and then others have the responsibility to use the correct version
3- change the `#printElementsOn:` method

I can perform the three options and propose a PR, but please tell me which one is the best for you.

**Comment by jecisc** [comment]
Other possibility is that if the deprecated method does exactly the same than the non deprecated on, we can put it in https://github.com/jecisc/PharoBackwardCompatibility and depend on this project on older pharo

**Comment by badetitou** [comment]
`ifError:` and `onErrorDo:` do not have the exact same feature. The first one calls a block with two parameters, whereas the second one calls the block with one parameter.

**Comment by badetitou** [comment]
Why not upgrading the line of code for P9.

Then write a package for PharoToVersion8 that is loaded in pharo before version 9

**Comment by badetitou** [comment]
Do you agree with #4 @jecisc?
Do you prefer another solution (until we fix this, it is not possible to use SmalltalkCI in P9.. which is a bit blocking for me)

**Comment by ClotildeToullec** [comment]
Hi ! Thanks for your work @badetitou ! I concur, we are kind of stuck while this is not fixed.
@jecisc it would be great if you had time to review this. Thanks !
